class InvalidEmailError(Exception):
    ...
class InvalidPhoneError(Exception):
    ...
class InvalidPhormathPhoneError(Exception):
    ...
class InvalidKeysError(Exception):
    ...
class InvalidTypeError(Exception):
    ...